name: Importar SVN a GitHub

on:
  workflow_dispatch:

jobs:
  import-svn:
    runs-on: ubuntu-latest

    steps:
    - name: Use Docker to handle SVN to Git import
      run: |
        # Pull a Docker image with git-svn pre-installed
        docker pull komljen/git-svn:latest
        
        # Run the Docker container to clone the SVN repository
        docker run --rm \
          -v $(pwd):/workspace \
          komljen/git-svn:latest \
          sh -c "
          git svn clone https://svn.code.sf.net/p/qautorouter/code/ --stdlayout /workspace/qautorouter-git
          "
        
        # Run Git commands to push to GitHub
        cd qautorouter-git
        git remote add origin https://x-access-token:${{ secrets.MY_TOKEN }}@github.com/${{ secrets.REPO_NAME }}.git
        git push -u origin --all
        git push origin --tags
