name: Importar SVN a GitHub

# Permite iniciar el workflow manualmente desde la pestaña Actions
on:
  workflow_dispatch:

jobs:
  import-svn:
    runs-on: ubuntu-20.04  # Cambiado a ubuntu-20.04 para que git-svn encuentre una versión compatible de Git

    steps:
    - name: Actualizar repositorios e instalar git-svn
      run: |
        sudo apt-get update
        sudo apt-get install -y git git-svn
    - name: Clonar el repositorio SVN
      run: |
        git svn clone https://svn.code.sf.net/p/qautorouter/code/ --stdlayout qautorouter-git
    - name: Configurar Git y hacer push a GitHub
      env:
        REPO_NAME: ${{ secrets.REPO_NAME }}
        MY_TOKEN: ${{ secrets.MY_TOKEN }}
      run: |
        cd qautorouter-git
        git remote add origin https://x-access-token:${MY_TOKEN}@github.com/${REPO_NAME}.git
        # Envía todas las ramas y etiquetas
        git push -u origin --all
        git push origin --tags
